# Generated by Django 6.0.6 on 2026-06-29 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_organizer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='minecraft_nick',
        ),
        migrations.AlterField(
            model_name='profile',
            name='discord_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='MinecraftAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('nickname', models.CharField(max_length=16)),
                ('avatar', models.URLField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minecraft_accounts', to='users.profile')),
            ],
        ),
    ]
