# Generated by Django 6.0.6 on 2026-06-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_is_organizer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minecraftaccount',
            old_name='avatar',
            new_name='skin_avatar',
        ),
        migrations.AlterField(
            model_name='minecraftaccount',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
