# Generated by Django 6.0.6 on 2026-06-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_avatar_minecraftaccount_skin_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discord_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
