# Generated by Django 6.0.6 on 2026-06-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_discord_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='global_name',
            new_name='display_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
