# Generated by Django 6.0.6 on 2026-07-04 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_global_name_profile_display_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='minecraftaccount',
            name='nickname',
            field=models.CharField(max_length=16, verbose_name='Ник'),
        ),
        migrations.AlterField(
            model_name='minecraftaccount',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minecraft_accounts', to='users.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='minecraftaccount',
            name='skin_avatar',
            field=models.URLField(blank=True, verbose_name='Аватарка скина'),
        ),
        migrations.AlterField(
            model_name='minecraftaccount',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID аккаунта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='discord_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Discord ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Отображаемое имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
