# Generated by Django 6.0.6 on 2026-06-30 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_rename_global_name_profile_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('info', models.TextField(blank=True, max_length=20000)),
                ('rules', models.TextField(blank=True, max_length=40000)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('max_players', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WIP', 'Строится'), ('RECRUITMENT', 'Набор'), ('READY', 'Готов'), ('ONGOING', 'Проводится'), ('FINISHED', 'Завершён')], default='WIP', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(help_text='HEX color #ff0000', max_length=7)),
                ('max_players', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CREATOR', 'Создатель'), ('ORGANIZER', 'Организатор'), ('PLAYER', 'Участник')], default='PLAYER', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='events.event')),
                ('minecraft_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.minecraftaccount')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='users.profile')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='events.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'profile'), name='unique_event_member')],
            },
        ),
    ]
