# Generated by Django 6.0.6 on 2026-06-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'Создатель'), ('SUPPORT', 'Ст. Организатор'), ('ORGANIZER', 'Организатор'), ('PLAYER', 'Участник')], default='PLAYER', max_length=20),
        ),
    ]
