# Generated by Django 6.0.6 on 2026-07-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_name_alter_event_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_team_creation',
            field=models.BooleanField(default=True, verbose_name='Разрешить участникам создавать команды'),
        ),
    ]
