# Generated by Django 6.0.6 on 2026-07-04 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_allow_team_creation'),
        ('users', '0006_alter_minecraftaccount_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allow_team_creation',
            field=models.BooleanField(default=True, help_text='Если нет - участники смогут присоедениться только к существующим командам', verbose_name='Разрешить участникам создавать свои команды'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Примерное или точное', null=True, verbose_name='Время окончания ивента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.TextField(blank=True, help_text='Все подробности об ивенте', max_length=20000, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_players',
            field=models.IntegerField(blank=True, help_text='Организаторы вне команд не учитываются', null=True, verbose_name='Максимум участников'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.TextField(blank=True, help_text='Все правила ивента', max_length=40000, verbose_name='Правила'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='Используется в URL для ссылки на страницу ивента. Например: peepo-hui', unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала ивента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('WIP', 'Строится'), ('RECRUITMENT', 'Набор'), ('READY', 'Готов'), ('ONGOING', 'Проводится'), ('FINISHED', 'Завершён')], default='WIP', max_length=20, verbose_name='Текущий статус ивента'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='events.event', verbose_name='Ивент участника'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время присоединения к ивенту'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='minecraft_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.minecraftaccount', verbose_name='Аккаунт участника'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='users.profile', verbose_name='Профиль участника'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'Создатель'), ('SUPPORT', 'Ст. Организатор'), ('ORGANIZER', 'Организатор'), ('PLAYER', 'Участник')], default='PLAYER', max_length=20, verbose_name='Роль участника'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='events.team', verbose_name='Команда участника'),
        ),
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, help_text='Цвет в HEX: #ff0000', max_length=7, null=True, verbose_name='Цвет кманды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event', verbose_name='Ивент команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='max_players',
            field=models.IntegerField(verbose_name='Максимум участников в команде'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название команды'),
        ),
    ]
