# Generated by Django 6.0.6 on 2026-07-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_allow_team_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_players_per_team',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников в команде'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_teams',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум команд'),
        ),
    ]
