# Generated by Django 6.0.6 on 2026-07-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_max_players_per_team_event_max_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='min_players_per_team',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимум участников в команде'),
        ),
    ]
