# Generated by Django 6.0.6 on 2026-07-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_min_players_per_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='max_players',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников в команде'),
        ),
    ]
