# Generated by Django 6.0.6 on 2026-10-10 07:53

from django.db import migrations

ROLE_TO_RANK = {"CREATOR": "0", "SUPPORT": "1", "ORGANIZER": "2", "PLAYER": "3"}
RANK_TO_ROLE = {v: k for k, v in ROLE_TO_RANK.items()}


def roles_to_numbers(apps, schema_editor):
   EventMember = apps.get_model("events", "EventMember")
   for old, new in ROLE_TO_RANK.items():
       EventMember.objects.filter(role=old).update(role=new)


def numbers_to_roles(apps, schema_editor):
   EventMember = apps.get_model("events", "EventMember")
   for new, old in RANK_TO_ROLE.items():
       EventMember.objects.filter(role=new).update(role=old)


class Migration(migrations.Migration):
   dependencies = [("events", "0007_alter_team_max_players")]
   operations = [migrations.RunPython(roles_to_numbers, numbers_to_roles)]