# Generated by Django 6.0.6 on 2026-10-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_roles_to_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='role',
            field=models.IntegerField(choices=[(0, 'Создатель'), (1, 'Ст. Организатор'), (2, 'Организатор'), (3, 'Участник')], default=3, verbose_name='Роль участника'),
        ),
    ]
